# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20171208_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.date(2018, 3, 5), verbose_name='event time'),
        ),
    ]
