# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20180305_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='event time'),
        ),
    ]
